/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as ReadingFeedIdIndexRouteImport } from './routes/reading/$feedId/index'
import { Route as LayoutFeedIdIndexRouteImport } from './routes/_layout/$feedId/index'
import { Route as ReadingFeedIdSlugRouteImport } from './routes/reading/$feedId/$slug'
import { Route as LayoutFeedIdItemIdRouteImport } from './routes/_layout/$feedId/$itemId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const ReadingFeedIdIndexRoute = ReadingFeedIdIndexRouteImport.update({
  id: '/reading/$feedId/',
  path: '/reading/$feedId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutFeedIdIndexRoute = LayoutFeedIdIndexRouteImport.update({
  id: '/$feedId/',
  path: '/$feedId/',
  getParentRoute: () => LayoutRoute,
} as any)
const ReadingFeedIdSlugRoute = ReadingFeedIdSlugRouteImport.update({
  id: '/reading/$feedId/$slug',
  path: '/reading/$feedId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutFeedIdItemIdRoute = LayoutFeedIdItemIdRouteImport.update({
  id: '/$feedId/$itemId',
  path: '/$feedId/$itemId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/': typeof LayoutIndexRoute
  '/$feedId/$itemId': typeof LayoutFeedIdItemIdRoute
  '/reading/$feedId/$slug': typeof ReadingFeedIdSlugRoute
  '/$feedId': typeof LayoutFeedIdIndexRoute
  '/reading/$feedId': typeof ReadingFeedIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/': typeof LayoutIndexRoute
  '/$feedId/$itemId': typeof LayoutFeedIdItemIdRoute
  '/reading/$feedId/$slug': typeof ReadingFeedIdSlugRoute
  '/$feedId': typeof LayoutFeedIdIndexRoute
  '/reading/$feedId': typeof ReadingFeedIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/$feedId/$itemId': typeof LayoutFeedIdItemIdRoute
  '/reading/$feedId/$slug': typeof ReadingFeedIdSlugRoute
  '/_layout/$feedId/': typeof LayoutFeedIdIndexRoute
  '/reading/$feedId/': typeof ReadingFeedIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/profile'
    | '/'
    | '/$feedId/$itemId'
    | '/reading/$feedId/$slug'
    | '/$feedId'
    | '/reading/$feedId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/'
    | '/$feedId/$itemId'
    | '/reading/$feedId/$slug'
    | '/$feedId'
    | '/reading/$feedId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/profile'
    | '/_layout/_authenticated'
    | '/_layout/'
    | '/_layout/$feedId/$itemId'
    | '/reading/$feedId/$slug'
    | '/_layout/$feedId/'
    | '/reading/$feedId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReadingFeedIdSlugRoute: typeof ReadingFeedIdSlugRoute
  ReadingFeedIdIndexRoute: typeof ReadingFeedIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/reading/$feedId/': {
      id: '/reading/$feedId/'
      path: '/reading/$feedId'
      fullPath: '/reading/$feedId'
      preLoaderRoute: typeof ReadingFeedIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/$feedId/': {
      id: '/_layout/$feedId/'
      path: '/$feedId'
      fullPath: '/$feedId'
      preLoaderRoute: typeof LayoutFeedIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/reading/$feedId/$slug': {
      id: '/reading/$feedId/$slug'
      path: '/reading/$feedId/$slug'
      fullPath: '/reading/$feedId/$slug'
      preLoaderRoute: typeof ReadingFeedIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/$feedId/$itemId': {
      id: '/_layout/$feedId/$itemId'
      path: '/$feedId/$itemId'
      fullPath: '/$feedId/$itemId'
      preLoaderRoute: typeof LayoutFeedIdItemIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFeedIdItemIdRoute: typeof LayoutFeedIdItemIdRoute
  LayoutFeedIdIndexRoute: typeof LayoutFeedIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFeedIdItemIdRoute: LayoutFeedIdItemIdRoute,
  LayoutFeedIdIndexRoute: LayoutFeedIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReadingFeedIdSlugRoute: ReadingFeedIdSlugRoute,
  ReadingFeedIdIndexRoute: ReadingFeedIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
